script("file/save.js")
script("file/button.js")
script("file/log.js")
script("package/main.js")
script("config/main.js")
script("compiler/main.js")
script("connector/session/connect.js")
importScripts("connector/firebase.js")